apiVersion: batch/v1
kind: Job
metadata:
  name: documentdb-perf-tester
spec:
  template:
    spec:
      containers:
      - name: documentdb-perf-tester
        image: 128194085353.dkr.ecr.us-west-2.amazonaws.com/documentdb-perf-tester:1.0
#        command: ["/mongo-perf/run"]
        command: ["/usr/bin/sleep", "infinity"]
      restartPolicy: Never
  backoffLimit: 4